In [ ]:
#Create a Classification model to predict whether a person makes over $50k a year

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('adult.csv')

In [ ]:
df.head()

Unnamed: 0         Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  \
0          39          State-gov       77516   Bachelors          13   
1          50   Self-emp-not-inc       83311   Bachelors          13   
2          38            Private      215646     HS-grad           9   
3          53            Private      234721        11th           7   
4          28            Private      338409   Bachelors          13   

            Unnamed: 5          Unnamed: 6      Unnamed: 7 Unnamed: 8  \
0        Never-married        Adm-clerical   Not-in-family      White   
1   Married-civ-spouse     Exec-managerial         Husband      White   
2             Divorced   Handlers-cleaners   Not-in-family      White   
3   Married-civ-spouse   Handlers-cleaners         Husband      Black   
4   Married-civ-spouse      Prof-specialty            Wife      Black   

  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12     Unnamed: 13  \
0       Male         2174            0           40   United-States   
1       Male            0            0           13   United-States   
2       Male            0            0           40   United-States   
3       Male            0            0           40   United-States   
4     Female            0            0           40            Cuba   

  Unnamed: 14  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K

In [ ]:
df.columns = ['Age','Workclass','Fnlwgt','Education','Education_num',
                  'Marital_status','Occupation','Relationship','Race',
                   'Sex','Capital_gain','Capital_loss','Hours_per_week','Native_country',
                  'Income']



In [ ]:
df.head()

Age          Workclass  Fnlwgt   Education  Education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital_status          Occupation    Relationship    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   Capital_gain  Capital_loss  Hours_per_week  Native_country  Income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [ ]:
df.shape

(32561, 15)

In [ ]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
Education_num     0
Marital_status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital_gain      0
Capital_loss      0
Hours_per_week    0
Native_country    0
Income            0
dtype: int64

In [ ]:
df.duplicated().sum()

24

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.shape

(32537, 15)

In [ ]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
Education_num      int64
Marital_status    object
Occupation        object
Relationship      object
Race              object
Sex               object
Capital_gain       int64
Capital_loss       int64
Hours_per_week     int64
Native_country    object
Income            object
dtype: object

In [ ]:
df['Income'].value_counts()

 <=50K    24698
 >50K      7839
Name: Income, dtype: int64

In [ ]:
df['Native_country'].value_counts()

 United-States                 29153
 Mexico                          639
 ?                               582
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Japan                            62
 Guatemala                        62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()
df['Workclass'] = lb.fit_transform(df['Workclass'])
df['Education'] = lb.fit_transform(df['Education'])
df['Marital_status'] = lb.fit_transform(df['Marital_status'])
df['Occupation'] = lb.fit_transform(df['Occupation'])
df['Relationship'] = lb.fit_transform(df['Relationship'])
df['Race'] = lb.fit_transform(df['Race'])
df['Sex'] = lb.fit_transform(df['Sex'])
df['Native_country'] = lb.fit_transform(df['Native_country'])
df['Income'] = lb.fit_transform(df['Income'])

In [ ]:
df.dtypes

Age               int64
Workclass         int64
Fnlwgt            int64
Education         int64
Education_num     int64
Marital_status    int64
Occupation        int64
Relationship      int64
Race              int64
Sex               int64
Capital_gain      int64
Capital_loss      int64
Hours_per_week    int64
Native_country    int64
Income            int64
dtype: object

In [ ]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
Education_num     0
Marital_status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital_gain      0
Capital_loss      0
Hours_per_week    0
Native_country    0
Income            0
dtype: int64

In [ ]:
df.drop(['Fnlwgt','Education_num', 'Marital_status', 'Relationship', 'Race','Capital_gain','Capital_loss'], axis=1, inplace=True)

In [ ]:
df.head()

Age  Workclass  Education  Occupation  Sex  Hours_per_week  Native_country  \
0   39          7          9           1    1              40              39   
1   50          6          9           4    1              13              39   
2   38          4         11           6    1              40              39   
3   53          4          1           6    1              40              39   
4   28          4          9          10    0              40               5   

   Income  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
df['Income'].value_counts()

0    24698
1     7839
Name: Income, dtype: int64

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
print(x.shape)
print(y.shape)

(32537, 7)
(32537,)


In [ ]:
x.head()

Age  Workclass  Education  Occupation  Sex  Hours_per_week  Native_country
0   39          7          9           1    1              40              39
1   50          6          9           4    1              13              39
2   38          4         11           6    1              40              39
3   53          4          1           6    1              40              39
4   28          4          9          10    0              40               5

In [ ]:
df['Native_country'].value_counts()

39    29153
26      639
0       582
30      198
11      137
2       121
33      114
8       106
19      100
5        95
9        90
23       81
35       80
3        75
22       73
6        70
40       67
24       62
13       62
31       60
4        59
36       51
14       44
20       43
32       37
27       34
29       31
10       29
12       29
7        28
21       24
17       20
1        19
38       19
25       18
37       18
41       16
28       14
16       13
18       13
34       12
15        1
Name: Native_country, dtype: int64

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Income, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24402, 7)
(8135, 7)
(24402,)
(8135,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
def apply_model(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    ypred = model.predict(x_test)
    print('Predictions\n',ypred)
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))
    cm = confusion_matrix(y_test,ypred)
    print('Confusion_matrix\n',cm)
    print('Classification_report\n',classification_report(y_test,ypred,zero_division=0))

In [ ]:
#1.APPLY DECISION TREE CLASSIFIER

In [ ]:
m1=DecisionTreeClassifier(criterion='entropy',max_depth=80,min_samples_split=60)
apply_model(m1,x_train,x_test,y_train,y_test)

Predictions
 [1 1 0 ... 0 0 0]
Training Score 0.8405458568969757
Testing Score 0.7998770743700061
Confusion_matrix
 [[5599  595]
 [1033  908]]
Classification_report
               precision    recall  f1-score   support

           0       0.84      0.90      0.87      6194
           1       0.60      0.47      0.53      1941

    accuracy                           0.80      8135
   macro avg       0.72      0.69      0.70      8135
weighted avg       0.79      0.80      0.79      8135



In [ ]:
### validate the result for precision,recall,f1score and accuracy
##[[TP=5599  FN=595]
## [FP=1033 TN=908]]
### precision = TP/(TP+FP), TN/(TN+FN)
### Recall - TP/(TP+FN), TN/(TN+FP)
###F1-Score - 2 * Precision * Recall /( Precision + Recall)
### Accuracy - (TP+TN)/(TP+FN+FP+TN)
precision0 = 5599/(5599+1033)
precision1 = 908/(908+595)
recall0 = 5599/(5599+595)
recall1 = 908/(908+1033)
print('Precision0:',round(precision0,2))
print('Precision1:',round(precision1,2))
print('Recall0:',round(recall0,2))
print('Recall1:',round(recall1,2))
f1s0 = 2*precision0*recall0/(precision0 + recall0)
f1s1 = 2*precision1*recall1/(precision1 + recall1)
print('F1-score0 : ',round(f1s0,2))
print('F1-score1 : ',round(f1s1,2))
accuracy = (5599+908)/(5599+595+1033+908)
print('Accuracy : ',round(accuracy,2))
##Percentage of Misclassification = # incorrect predictions / # total predictions
##Percentage of Misclassification = (false positive + false negative) / (total predictions)
misclassification_percentage = (1033+595)/(5599+595+1033+908)
print(' percentage of misclassification = ',misclassification_percentage)

Precision0: 0.84
Precision1: 0.6
Recall0: 0.9
Recall1: 0.47
F1-score0 :  0.87
F1-score1 :  0.53
Accuracy :  0.8
 percentage of misclassification =  0.20012292562999384


In [ ]:
#2.APPLY SVC CLASSIFIER

In [ ]:
m2=SVC(kernel='linear',C=1)
apply_model(m2,x_train,x_test,y_train,y_test)

Predictions
 [0 0 0 ... 0 0 0]
Training Score 0.7582985001229408
Testing Score 0.76140135218193
Confusion_matrix
 [[6194    0]
 [1941    0]]
Classification_report
               precision    recall  f1-score   support

           0       0.76      1.00      0.86      6194
           1       0.00      0.00      0.00      1941

    accuracy                           0.76      8135
   macro avg       0.38      0.50      0.43      8135
weighted avg       0.58      0.76      0.66      8135



In [ ]:
### validate the result for precision,recall,f1score and accuracy
##[[TP=6194  FN=0]
## [FP=1941 TN=0]]
### precision = TP/(TP+FP), TN/(TN+FN)
### Recall - TP/(TP+FN), TN/(TN+FP)
###F1-Score - 2 * Precision * Recall /( Precision + Recall)
### Accuracy - (TP+TN)/(TP+FN+FP+TN)
precision0 = 6194/(6194+1941)
precision1 = 0
recall0 = 6194/(6194+0)
recall1 = 0
print('Precision0:',round(precision0,2))
print('Precision1:',round(precision1,2))
print('Recall0:',round(recall0,2))
print('Recall1:',round(recall1,2))
f1s0 = 2*precision0*recall0/(precision0 + recall0)
try:
  f1s1 = 2*precision1*recall1/(precision1 + recall1)
except ZeroDivisionError:
   f1s1=0
print('F1-score0 : ',round(f1s0,2))
print('F1-score1 : ',round(f1s1,2))
accuracy = (6194+0)/(6194+0+1941+0)
print('Accuracy : ',round(accuracy,2))
##Percentage of Misclassification = # incorrect predictions / # total predictions
##Percentage of Misclassification = (false positive + false negative) / (total predictions)
misclassification_percentage = (1941+0)/(6194+0+1941+0)
print(' percentage of misclassification = ',misclassification_percentage)

Precision0: 0.76
Precision1: 0
Recall0: 1.0
Recall1: 0
F1-score0 :  0.86
F1-score1 :  0
Accuracy :  0.76
 percentage of misclassification =  0.23859864781807008


In [ ]:
#3.APPLY RANDOM FOREST CLASSIFIER

In [ ]:
m3=RandomForestClassifier(n_estimators=90,criterion='entropy',max_depth=60,min_samples_split=40)
apply_model(m3,x_train,x_test,y_train,y_test)

Predictions
 [0 0 0 ... 0 0 0]
Training Score 0.8458323088271453
Testing Score 0.8205285802089736
Confusion_matrix
 [[5762  418]
 [1042  913]]
Classification_report
               precision    recall  f1-score   support

           0       0.85      0.93      0.89      6180
           1       0.69      0.47      0.56      1955

    accuracy                           0.82      8135
   macro avg       0.77      0.70      0.72      8135
weighted avg       0.81      0.82      0.81      8135



In [ ]:
### validate the result for precision,recall,f1score and accuracy
##[[TP=5762  FN=418]
## [FP=1042 TN=913]]
### precision = TP/(TP+FP), TN/(TN+FN)
### Recall - TP/(TP+FN), TN/(TN+FP)
###F1-Score - 2 * Precision * Recall /( Precision + Recall)
### Accuracy - (TP+TN)/(TP+FN+FP+TN)
precision0 = 5762/(5762+1042)
precision1 = 913/(913+418)
recall0 = 5762/(5762+418)
recall1 = 913/(913+1042)
print('Precision0:',round(precision0,2))
print('Precision1:',round(precision1,2))
print('Recall0:',round(recall0,2))
print('Recall1:',round(recall1,2))
f1s0 = 2*precision0*recall0/(precision0 + recall0)
f1s1 = 2*precision1*recall1/(precision1 + recall1)
print('F1-score0 : ',round(f1s0,2))
print('F1-score1 : ',round(f1s1,2))
accuracy = (5762+913)/(5762+418+1042+913)
print('Accuracy : ',round(accuracy,2))
##Percentage of Misclassification = # incorrect predictions / # total predictions
##Percentage of Misclassification = (false positive + false negative) / (total predictions)
misclassification_percentage = (1042+418)/(5762+418+1042+913)
print(' percentage of misclassification = ',misclassification_percentage)

Precision0: 0.85
Precision1: 0.69
Recall0: 0.93
Recall1: 0.47
F1-score0 :  0.89
F1-score1 :  0.56
Accuracy :  0.82
 percentage of misclassification =  0.17947141979102643


In [ ]:
#4.APPLY LOGISTIC REGRESSION

In [ ]:
m4=LogisticRegression(solver='liblinear')
apply_model(m4,x_train,x_test,y_train,y_test)

Predictions
 [0 0 0 ... 0 0 0]
Training Score 0.7610031964593066
Testing Score 0.7595574677320222
Confusion_matrix
 [[5841  324]
 [1632  338]]
Classification_report
               precision    recall  f1-score   support

           0       0.78      0.95      0.86      6165
           1       0.51      0.17      0.26      1970

    accuracy                           0.76      8135
   macro avg       0.65      0.56      0.56      8135
weighted avg       0.72      0.76      0.71      8135



In [ ]:
### validate the result for precision,recall,f1score and accuracy
##[[TP=5841  FN=324]
## [FP=1632 TN=338]]
### precision = TP/(TP+FP), TN/(TN+FN)
### Recall - TP/(TP+FN), TN/(TN+FP)
###F1-Score - 2 * Precision * Recall /( Precision + Recall)
### Accuracy - (TP+TN)/(TP+FN+FP+TN)
precision0 = 5841/(5841+1632)
precision1 = 338/(338+324)
recall0 = 5841/(5841+324)
recall1 = 338/(338+1632)
print('Precision0:',round(precision0,2))
print('Precision1:',round(precision1,2))
print('Recall0:',round(recall0,2))
print('Recall1:',round(recall1,2))
f1s0 = 2*precision0*recall0/(precision0 + recall0)
f1s1 = 2*precision1*recall1/(precision1 + recall1)
print('F1-score0 : ',round(f1s0,2))
print('F1-score1 : ',round(f1s1,2))
accuracy = (5841+338)/(5841+324+1632+338)
print('Accuracy : ',round(accuracy,2))
##Percentage of Misclassification = # incorrect predictions / # total predictions
##Percentage of Misclassification = (false positive + false negative) / (total predictions)
misclassification_percentage = (1632+324)/(5841+324+1632+338)
print(' percentage of misclassification = ',misclassification_percentage)

Precision0: 0.78
Precision1: 0.51
Recall0: 0.95
Recall1: 0.17
F1-score0 :  0.86
F1-score1 :  0.26
Accuracy :  0.76
 percentage of misclassification =  0.24044253226797788


In [ ]:
#5.APPLY KNN CLASSIFIER

In [ ]:
m5=KNeighborsClassifier(n_neighbors=35)
apply_model(m5,x_train,x_test,y_train,y_test)

Predictions
 [0 0 0 ... 0 0 0]
Training Score 0.7934185722481764
Testing Score 0.7842655193607867
Confusion_matrix
 [[5638  577]
 [1178  742]]
Classification_report
               precision    recall  f1-score   support

           0       0.83      0.91      0.87      6215
           1       0.56      0.39      0.46      1920

    accuracy                           0.78      8135
   macro avg       0.69      0.65      0.66      8135
weighted avg       0.76      0.78      0.77      8135



In [ ]:
### validate the result for precision,recall,f1score and accuracy
##[[TP=5638  FN=577]
## [FP=1178 TN=742]]
### precision = TP/(TP+FP), TN/(TN+FN)
### Recall - TP/(TP+FN), TN/(TN+FP)
###F1-Score - 2 * Precision * Recall /( Precision + Recall)
### Accuracy - (TP+TN)/(TP+FN+FP+TN)
precision0 = 5638/(5638+1178)
precision1 = 742/(742+577)
recall0 = 5638/(5638+577)
recall1 = 742/(742+1178)
print('Precision0:',round(precision0,2))
print('Precision1:',round(precision1,2))
print('Recall0:',round(recall0,2))
print('Recall1:',round(recall1,2))
f1s0 = 2*precision0*recall0/(precision0 + recall0)
f1s1 = 2*precision1*recall1/(precision1 + recall1)
print('F1-score0 : ',round(f1s0,2))
print('F1-score1 : ',round(f1s1,2))
accuracy = (5638+742)/(5638+577+1178+742)
print('Accuracy : ',round(accuracy,2))
##Percentage of Misclassification = # incorrect predictions / # total predictions
##Percentage of Misclassification = (false positive + false negative) / (total predictions)
misclassification_percentage = (1178+577)/(5638+577+1178+742)
print(' percentage of misclassification = ',misclassification_percentage)

Precision0: 0.83
Precision1: 0.56
Recall0: 0.91
Recall1: 0.39
F1-score0 :  0.87
F1-score1 :  0.46
Accuracy :  0.78
 percentage of misclassification =  0.21573448063921327


In [ ]:
#THE MODEL THAT GIVES BEST ACCURACY IS RANDOM FOREST CLASSIFIER.It gives us an accuracy score of 82%

In [ ]:
ypred_res=m3.predict(x_test)
print("Predictions for Random Forest:",ypred_res)

Predictions for Random Forest: [0 0 0 ... 0 0 0]


In [ ]:
import collections,numpy
a=numpy.array(ypred_res)
collections.Counter(a)

Counter({0: 6804, 1: 1331})

In [ ]:
#RANDOM FOREST CLASSIFIER MODEL PREDICTS THAT 1331 PEOPLE MAKE OVER $50K A YEAR